### PR TITLE
add Network Stack type for Atmel winc1500

### PR DESCRIPTION
**Pull request by brianjang**
added feature : ATWINC_IPv4

### CODE REVIEW

**Comment by yogpan01** [comment]
@brianjang Hi, can you please also mention the other PRs here , which you created for sal layer to enable WiFi support for Socket ?

**Comment by brianjang** [comment]
@yogpan01  Hi. the below lists is our PRs for our IP Stack support.

1. m2mconnectionhandlerimple.cpp : \yotta_modules\mbed-client-mbed-os\source\
 ```
M2MConnectionHandlerPimpl() 
 : case M2MInterface::ATWINC_IPv4: 
        _socket_stack = SOCKET_STACK_ATWINC_IPV4;
        break;
```

2. socket_types.h : ..\yotta_modules\sal\sal\
``` 
socket_stack_t : SOCKET_STACK_ATWINC_IPV4
```

3. m2minterface.h : ..\yotta_modules\mbed-client\mbed-client\
```
NetworkStack : ATWINC_IPv4
```

**Comment by teetak01** [comment]
Would we not also need some implementation in m2minterfaceimpl.cpp?

**Comment by brianjang** [comment]
@teetak01 
Yes, you don't need to implement in m2minterfaceimpl.cpp (this is handled by ARM mbed team)

**Comment by yogpan01** [comment]
@brianjang Can you please rebase this PR from master ? We can then merge this PR when it passes the CR.

**Comment by brianjang** [comment]
@yogpan01 

Hi, I used "Update branch" button to merge my branch to master. and i got the result, "All checks have passed"
if i have any missing point, please let me know.

**Comment by Areontar** [comment]
Hi @yogpan01 

Could we sync on this merge, I think @brianjang did merge with master, but then another PR got rolled in before this one could be merged.  It would be good to set a time or a PR queue since this might be across  timezones.

**Pull request merged**
