### PR TITLE
Fix re-registration case on Linux

### PR DESCRIPTION
**Pull request by anttiylitokola**

### CODE REVIEW

**Comment by anttiylitokola** [comment]
@yogpan01

**Comment by anttiylitokola** [comment]
@yogpan01

**Comment by yogpan01** [comment]
This needs to be tested with Cloud as well before can be merged as there were issues before with stop_listening API calls

**Comment by ErkkiMehtala** [comment]
FYI, those 2 re-register cases are failing until this is merged.

**Comment by ErkkiMehtala** [comment]
I tested this PR in cloud, does not work there. There is task for supporting this: @kuggenhoffen http://jira.arm.com/browse/IOTCLT-1015.

Used test case:
python clitest.py -v --reset --tc O5020100F014 --env_cfg env_cfg_cases_using_services.json --type hardware --bin ../mbed-client-testapp/mbed-client-testapp.bin

Relevant part from log:
...
00:55:22.890 | D1 <-- DutThread: [1540][INFO][CCCT]: ###########
00:55:22.911 | D1 <-- DutThread: [1541][INFO][CCCT]: Registered!
00:55:22.933 | D1 <-- DutThread: [1542][INFO][CCCT]: ###########
00:55:22.955 | D1 <-- DutThread: [1543][DBG ][testcmd]: cmd_ready_cb(0)
00:55:22.967 | D1 <-- DutThread: [1544][INFO][CCCT]: ASync cmd result was 1
00:55:22.988 | D1 <-- DutThread: retcode: 0
00:55:22.989 | D1 <-> DutThread: Got reponse
00:55:22.995 | TC     MainThread: Waiting for 5 seconds
00:55:23.000 | D1 <<< DutThread: [1545][INFO][CCCT]: ################################
00:55:23.022 | D1 <<< DutThread: [1546][DBG ][mClt]: M2MNsdlInterface::registration_time - value (in seconds) 2
00:55:23.032 | D1 <<< DutThread: [1547][INFO][CCCT]: SUCCESS: cloud_client setup done
00:55:23.055 | D1 <<< DutThread: [1548][DBG ][mClt]: M2MConnectionHandlerPimpl::connection_tasklet_event_handler
00:55:23.065 | D1 <<< DutThread: [1549][INFO][CCCT]: ################################
00:55:23.088 | D1 <<< DutThread: [1550][DBG ][mClt]: connection_tasklet_event_handler - ESocketReadytoRead
00:55:23.099 | D1 <<< DutThread: [1551][DBG ][mClt]: M2MConnectionHandlerPimpl::receive_handler()
00:55:23.109 | D1 <<< DutThread: [1552][DBG ][mClt]: mbedtls_timing_get_delay
00:55:23.121 | D1 <<< DutThread: [1553][DBG ][mClt]: mbedtls_timing_get_delay - ret -1
00:55:23.132 | D1 <<< DutThread: [1554][DBG ][mClt]: mbedtls_timing_set_delay - intermediate: 0
00:55:23.142 | D1 <<< DutThread: [1555][DBG ][mClt]: mbedtls_timing_set_delay - final: 0
00:55:23.154 | D1 <<< DutThread: [1556][DBG ][mClt]: mbedtls_timing_set_delay - stop
00:55:23.165 | D1 <<< DutThread: [1557][DBG ][mClt]: mbedtls_timing_get_delay
00:55:23.176 | D1 <<< DutThread: [1558][DBG ][mClt]: mbedtls_timing_get_delay - ret -1
00:55:23.187 | D1 <<< DutThread: [1559][DBG ][mClt]: M2MConnectionHandlerPimpl::receive_from_socket
00:55:23.198 | D1 <<< DutThread: [1560][DBG ][mClt]: M2MConnectionHandlerPimpl::receive_from_socket recv size -3001
00:55:27.998 | D1 <-> MainThread: CMD 'lwm2m-client register' timeout=1475049507 time=1475049327
00:55:27.999 | D1 --> DutThread: lwm2m-client register
00:55:28.018 | D1 <-- DutThread: [1561][DBG ][testcmd]: cmd_ready_cb(0)
00:55:28.034 | D1 <-- DutThread: [1562][DBG ][MCCT]: [MbedCloudClient] setup()
00:55:28.056 | D1 <-- DutThread: [1563][DBG ][MCCT]: [MbedCloudClient] [ERROR] setup() called, but MbedCloudClient is already instantiated
00:55:29.001 | D1     MainThread: Waiting for response... timeout=178
00:55:30.003 | D1     MainThread: Waiting for response... timeout=177
...

**Comment by yogpan01** [comment]
rebuild

**Pull request merged**
