### PR TITLE
Callback memory optimizations

### PR DESCRIPTION
**Pull request by TeroJaasko**

### CODE REVIEW

**Comment by TeroJaasko** [comment]
@anttiylitokola @yogpan01 @karsev : work in progress, unless you have objections, I'll remove the rest of callbacks from the M2MBase and its children.

**Comment by yogpan01** [comment]
Looks good to me. Continue with the rest of the optimization work.

**Comment by TeroJaasko** [comment]
rebuild

**Comment by TeroJaasko** [comment]
I removed the rest of callbacks but left M2MResourceInstance::_resource_callback. That information could be removed completely / replaced with more efficient way on next refactoring phase as there already is up to three pointers backwards in the object hierarchy and these need to be consolidated.

**Comment by TeroJaasko** [comment]
This will be merged into memory_optimizations -branch first and then to rel1.2.

**Comment by TeroJaasko** [comment]
Fixed the unit tests and two bugs they found from actual implementation and rewrote the commit history.

**Comment by TeroJaasko** [comment]
Merged to memory_optimizations on https://github.com/ARMmbed/mbed-client/commit/b36e53f646e2c42a16c6452482b791a4491bef03

**Pull request closed without merging**
