### PR TITLE
Remove unnecessary includes of stdio.h, cstdio and stdexp

### PR DESCRIPTION
**Pull request by TeroJaasko**
The stdio related headers are causing headache on some
more constrained environments. Remove those as they are not
really even needed as one can and should be using the
eg. stdint and stdlib.

### CODE REVIEW

**Comment by TeroJaasko** [comment]
@yogpan01 @anttiylitokola

**Comment by kjbracey-arm** [comment]
stdexp?

Including stdint.h from C++ in a public header file can be a slight trap due to the silly C99 STDC_LIMIT_MACROS thing, which some C++ compilers do.

Would generally recommend using ns_types.h to get it, as it deals with that trap (by always defining those macros).

**Comment by kjbracey-arm** [comment]
BTW, what doesn't have stdio? Agree that these particular headers shouldn't be needing to include it, but we've got an awful lot of code that relies on it.

**Comment by yogpan01** [comment]
rebuild

**Comment by yogpan01** [comment]
rebuild

**Comment by TeroJaasko** [comment]
rebuild

**Comment by TeroJaasko** [comment]
rebuild

**Comment by TeroJaasko** [comment]
rebuild

**Comment by TeroJaasko** [comment]
rebuild

**Pull request merged**
