### PR TITLE
Add new functions to fw API.

### PR DESCRIPTION
**Pull request by simosillankorva**

### CODE REVIEW

**Comment by yogpan01** [comment]
@simosillankorva For the cpp file , there seems to be extra empty lines between the code lines, can you configure your IDE to remove that?

**Comment by simosillankorva** [comment]
@yogpan01 I prefer to have empty lines.

**Comment by JanneKiiskila** [comment]
Needs rebasing!

**Comment by JanneKiiskila** [comment]
retry-needed, RaaS failure; 
10:33:32 Exception in thread D1:
10:33:32 Traceback (most recent call last):
10:33:32   File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
10:33:32     self.run()
10:33:32   File "/usr/lib/python2.7/threading.py", line 763, in run
10:33:32     self.__target(*self.__args, **self.__kwargs)
10:33:32   File "/builds/ws/mbed-client_smoke_tests_hw/mbed-clitest/mbed_clitest/DeviceConnectors/DutRaas.py", line 149, in run
10:33:32     line = self._readline()
10:33:32   File "/builds/ws/mbed-client_smoke_tests_hw/mbed-clitest/mbed_clitest/DeviceConnectors/DutRaas.py", line 141, in _readline
10:33:32     line = self._raas_resource.readline(timeout = 1)
10:33:32   File "build/bdist.linux-x86_64/egg/raas_client/resources/Base.py", line 338, in readline
10:33:32     line = self.data_channel.readline()
10:33:32   File "build/bdist.linux-x86_64/egg/raas_client/generic/Channels.py", line 55, in readline
10:33:32     self._s_buffer += newbytes.decode() if hasattr(newbytes, 'decode') else newbytes
10:33:32 UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 207: ordinal not in range(128)
10:33:32 
10

**Pull request merged**
