### PR TITLE
Fix post request handling in object and object instance level

### PR DESCRIPTION
**Pull request by anttiylitokola**

### CODE REVIEW

**Comment by anttiylitokola** [comment]
rebuild

**Comment by anttiylitokola** [comment]
@yogpan01

**Comment by teetak01** [comment]
rebuild

**Comment by teetak01** [comment]
rebuild

**Comment by teetak01** [comment]
rebuild

**Comment by teetak01** [comment]
FYI: tested with new HW-suites

**Comment by yogpan01** [comment]
@anttiylitokola @teetak01 Do you guys think this is now in good shape to merge ? Please merge it in then.

**Pull request merged**
