### PR TITLE
Add couple more coap message traces

### PR DESCRIPTION
**Pull request by kuggenhoffen**
Added message code, type and url traces just to get some more info.

### CODE REVIEW

**Comment by kuggenhoffen** [comment]
@yogpan01 @anttiylitokola @TeroJaasko

**Comment by TeroJaasko** [comment]
+1

**Comment by yogpan01** [comment]
rebuild

**Comment by teetak01** [comment]
rebuild

**Comment by teetak01** [comment]
rebuild

**Comment by teetak01** [comment]
rebuild

**Comment by teetak01** [comment]
rebuild

**Comment by yogpan01** [comment]
rebuild

**Comment by TeroJaasko** [comment]
This looks a change done to solve some debugging problem and could be merged after rebasing.

**Comment by yogpan01** [comment]
Merging this PR as the build compiles and runs fine, there are some CI side issue causing some failures in testcase run.

**Comment by TeroJaasko** [comment]
Rebased this branch with current master, resolved the merge conflict and force pushed.

**Pull request merged**
