### PR TITLE
Fix re-registration case in cloud mode.

### PR DESCRIPTION
**Pull request by anttiylitokola**
Fix possible null pointer access in m2mnsdlinterface.

### CODE REVIEW

**Comment by anttiylitokola** [comment]
rebuild

**Comment by anttiylitokola** [comment]
rebuild

**Comment by anttiylitokola** [comment]
rebuild

**Comment by anttiylitokola** [comment]
rebuild

**Comment by yogpan01** [comment]
+1

**Comment by anttiylitokola** [comment]
rebuild

**Comment by anttiylitokola** [comment]
rebuild

**Pull request merged**
