### PR TITLE
Coap option tidy

### PR DESCRIPTION
**Pull request by AnttiKauppila**
Mbed-client-c has been refactored to be more memory efficient. 

Changes in mbed-client-c has been updated to mbed-client side in this PR

### CODE REVIEW

**Comment by AnttiKauppila** [comment]
rebuild

**Comment by anttiylitokola** [comment]
rebuild

**Comment by anttiylitokola** [comment]
rebuild

**Comment by anttiylitokola** [comment]
rebuild

**Comment by anttiylitokola** [comment]
rebuild

**Comment by anttiylitokola** [comment]
prkl

**Pull request merged**
