### PR TITLE
Fix for over-writing subscription token

### PR DESCRIPTION
**Pull request by yogpan01**
This commit includes
 - Fix to prevent over writing subscription token with normal GET request tokens.

### CODE REVIEW

**Comment by yogpan01** [comment]
@janjongboom @stephenkyle-ARM In case you would like to test with your subscription use case.

**Comment by ciarmcom** [comment]
Failed

**Comment by yogpan01** [comment]
rebuild

**Comment by ciarmcom** [comment]
Failed

**Comment by anttiylitokola** [comment]
rebuild

**Comment by yogpan01** [comment]
@anttiylitokola Morpheus CI needs to be checked today, if it is still broken, may be disable for today

**Comment by janjongboom** [comment]
On first look it seems to work 👍

**Comment by yogpan01** [comment]
rebuild

**Comment by teetak01** [comment]
rebuild

**Comment by teetak01** [comment]
rebuild

**Comment by teetak01** [comment]
rebuild

**Comment by yogpan01** [comment]
rebuild

**Comment by yogpan01** [comment]
rebuild

**Pull request merged**
