### PR TITLE
Ignore Duplicate CoAP messages.

### PR DESCRIPTION
**Pull request by yogpan01**
This commit includes
 - Ignore CoAP messages if they are duplicated. Check happens on C++ side
   and silently ignores these messages.

### CODE REVIEW

**Comment by anttiylitokola** [comment]
rebuild

**Comment by teetak01** [comment]
rebuild

**Comment by yogpan01** [comment]
rebuild

**Comment by yogpan01** [comment]
rebuild

**Comment by yogpan01** [comment]
rebuild

**Comment by teetak01** [comment]
rebuild

**Comment by yogpan01** [comment]
This is not required as Duplication message is handled internally by mbed-client-c.

**Pull request closed without merging**
