### PR TITLE
Force publishing of device resource

### PR DESCRIPTION
**Pull request by jankii01**
To enable the update testing & development, it is not showing up in portal otherwise.
Ref:; Marcus Chang / IOTCLT-1284

### CODE REVIEW

**Comment by TeroJaasko** [comment]
How about the 6 other places where a resource is created on this class? This change makes code behave differently depending of which of the methods is used first. And please add a some kind of comment there that this change may or may not break the specification.

**Comment by anttiylitokola** [comment]
Yes, let's publish all the resources for now, mandatory and the optional ones.

**Comment by jankii01** [comment]
One test case fails! The 1st test is failing. 
`16:24:40 | I0010110F062 |   fail  | GET:No response received withi |             | 174.606081 [|]`

**Comment by teetak01** [comment]
rebuild

**Comment by jankii01** [comment]
https://github.com/ARMmbed/mbed-client/pull/350 - replaces this.

**Pull request closed without merging**
