### PR TITLE
Update Introduction.md

### PR DESCRIPTION
**Pull request by anttiylitokola**
@yogpan01, @peknis01, can you check this change? Also I'm not sure if this in right documentation file.

### CODE REVIEW

**Comment by peknis01** [comment]
Up to Yogesh to approve the contents and the place for this addition. I will then take care of the language (nothing much to clean up).

**Comment by yogpan01** [comment]
Looks good to me, don't just merge it yet. We have a release coming up so we will merge all the requests after that.

**Comment by yogpan01** [comment]
@anttiylitokola @peknis01 should this be merged and public site documentation be updated ?

**Comment by peknis01** [comment]
At least I have been waiting for green light from you. Go ahead and merge. I'll then build the new version of the document to docs site.

**Pull request merged**
