### PR TITLE
Rework mem opt m2m virtual

### PR DESCRIPTION
**Pull request by JaniSuonpera**
Rebased with master

### CODE REVIEW

**Comment by yogpan01** [comment]
@TeroJaasko didnt you already rebase memory_optimizatons branch with master? Will this PR now duplicate git commit history again ?

**Comment by TeroJaasko** [comment]
Yes, this branch needs cleanup. Or was this PR was supposed to be against master? If so, just press the edit-button and select the target branch to be master, not memory_optimizations.

**Comment by JaniSuonpera** [comment]
Maybe I should do it this change directly to master branch.

**Comment by JaniSuonpera** [comment]
Now unit tests pass rate is 15/18 with memory_optimizations branch of mbed-client-c.

Failing test cases are:
m2mresource
m2mresourceinstance
m2mbase

**Comment by TeroJaasko** [comment]
Thsi went in via master, closing PR.

**Pull request closed without merging**
