### PR TITLE
Ram savings

### PR DESCRIPTION
**Pull request by TeroJaasko**

### CODE REVIEW

**Comment by yogpan01** [comment]
@anttiylitokola @teetak01 : Can you run some corner cases on this PR ? Especially Device object related ones, which we fixed last week.

**Comment by anttiylitokola** [comment]
rebuild

**Comment by teetak01** [comment]
Device Object, Observation and some other basic connector-cases at least work fine.

**Comment by TeroJaasko** [comment]
@anttiylitokola : I just started a e2e-job for this but could you sanity-check the two new commits too.

**Pull request merged**
