### PR TITLE
Update Howto.md

### PR DESCRIPTION
**Pull request by anttiylitokola**
Example of using overloaded set_execute_function.

### CODE REVIEW

**Comment by anttiylitokola** [comment]
@yogpan01, @peknis01, something to check.

**Comment by peknis01** [comment]
And the same comment goes for this as well. If Yogesh is ok with the contents, I will check the language and the format anyway before publishing.

**Comment by yogpan01** [comment]
Looks ok, how about the documentation related with value_updated() functionality ?

**Comment by yogpan01** [comment]
@anttiylitokola update the Execute operation documentation done here as well https://github.com/ARMmbed/mbed-client/blob/datatype_exercise/docs/dev_man_serv_enable.md#the-execute-operation

**Comment by anttiylitokola** [comment]
@yogpan01, it's already done in this PR https://github.com/ARMmbed/mbed-client/pull/171

**Comment by yogpan01** [comment]
@anttiylitokola You also need to cover the overloaded function part in that PR. Its in different sections so cover it on both the places.

**Comment by teetak01** [comment]
rebuild

**Comment by teetak01** [comment]
rebuild

**Pull request merged**
