### PR TITLE
Change port number to 0

### PR DESCRIPTION
**Pull request by simosillankorva**
This should pick a the port from the private range.

### CODE REVIEW

**Comment by kjbracey-arm** [comment]
I thought that had been already been fixed in some very similar looking illogical code, by relying on the network stack doing sensible allocation (triggered by setting 0 to this port variable).

Leaving it to the stack is better, as it can avoid ports in use, whereas you might hit something by accident.

At the time this was writing, lwIP and Nanostack certainly weren't doing proper randomisation, but I think you can rely on it now (presumably the PAL/NSAPI would do randomisation if they knew they were on a broken stack).

**Comment by simosillankorva** [comment]
Leaving it to the stack would be better if all the stacks would randomize the port with 0. But it may not be the case as we use also other stacks, not just lwIP and Nanostack.

If the PAL would hadle this in "broken stacks" it would be ok, but current that is prabably not the case as they dont like to do anything extra.

**Comment by kjbracey-arm** [comment]
Double-check with Janne, as I have a feeling that other mbed client code (maybe examples) are already leaving it to the PAL, unless that got backed out. Be consistent.

Maybe mbed-client needs a central "choose a random port" function to cover up PAL differences.

**Comment by simosillankorva** [comment]
Changed to 0 as Janne told that we are using it already in some other places. Lets hope that the PAL will handle the possible problems...

**Comment by simosillankorva** [comment]
rebuild

**Comment by simosillankorva** [comment]
@yogpan01 @TeroJaasko @anttiylitokola Could someone take a look at this pull request? It is quite trivial change so review should not take much time.

**Comment by yogpan01** [comment]
Linked with #343 , we first get in the previous PR and then merge rest of the stuff in.

**Pull request merged**
