### PR TITLE
Documentation for new APIs added in mbed Client

### PR DESCRIPTION
**Pull request by yogpan01**
This commit includes
 - Description for new APIs added in mbed Client through
   https://github.com/ARMmbed/mbed-client/pull/218

### CODE REVIEW

**Comment by yogpan01** [comment]
@peknis01 : Please review the changes . New APIs are added through PR #218

**Comment by yogpan01** [comment]
@anttiylitokola Please follow this with @peknis01 and merge when review is done and docs published.

**Comment by peknis01** [comment]
Oh gosh, I guess I did this wrong way. I already edited the docs in master.

**Comment by peknis01** [comment]
So I edited the h files in master. I guess that should be ok. Now, looking this change in the doc_update branch.

**Comment by peknis01** [comment]
Editorial changes made. Questions: 

- mbed Client requires a random number generator to feed into the underlying SSL library. -> to feed what into the SSL library?

- mbed Client provides an API to add your own entropy source to feed into underlying SSL library. -> to feed what into the SSL library?

**Comment by yogpan01** [comment]
@peknis01 Here are the answers:
* mbed Client requires a random number generator to feed true random number into the underlying SSL library.
* mbed Client provides an API to add your own entropy source into underlying SSL library. Entropy source is directly added into SSL library.

**Comment by peknis01** [comment]
@yogpan01 Thanks. The doc should be ok now.

**Pull request merged**
