### PR TITLE
change void ip6tos => uint_fast8_t ip6tos

### PR DESCRIPTION
**Pull request by teetak01**
change void ip6tos => uint_fast8_t ip6tos to reflect changes in nanostack-libservice

### CODE REVIEW

**Comment by teetak01** [comment]
@yogpan01 Changes in nanostack-libservice require updating the stubs in several of our libs

**Comment by teetak01** [comment]
CC: @tommikas

**Comment by SeppoTakalo** [comment]
Uups.. I accidentally the same thing https://github.com/ARMmbed/mbed-client/pull/258
is this bad?

**Comment by teetak01** [comment]
I think your PR is fine, this can be closed. Besides you have properly the return 0; there.

**Pull request closed without merging**
