### PR TITLE
Memoptimisation virtual methods

### PR DESCRIPTION
**Pull request by kuggenhoffen**

### CODE REVIEW

**Comment by kuggenhoffen** [comment]
@TeroJaasko @yogpan01 @anttiylitokola

**Comment by yogpan01** [comment]
@kuggenhoffen valgrind errors ?

**Comment by anttiylitokola** [comment]
Yep, it's failing due to Valgrind errors. I thought we agree to enable some limits in a CI for Valgrind errors but looks that those are not yet fixed. I'll loosen the rule for now.

**Comment by anttiylitokola** [comment]
Looks like previous builds have been passed and there is zero Valgrind errors, so this change caused some regression in Valgrind run.

**Comment by kuggenhoffen** [comment]
I didn't have time to check the failing build yet, also need to check couple of warnings that came with this.

**Comment by kuggenhoffen** [comment]
rebuild

**Comment by kuggenhoffen** [comment]
rebuild

**Pull request merged**
