### PR TITLE
Add new API to set value updated callback to individual object

### PR DESCRIPTION
**Pull request by anttiylitokola**

### CODE REVIEW

**Comment by anttiylitokola** [comment]
@yogpan01, please review. Unit tests will be updated if this new API looks ok.

**Comment by yogpan01** [comment]
@devran01 Can you please check this up and provide your feedback, if this is satisfying your use case ?

**Comment by devran01** [comment]
@anttiylitokola @yogpan01 Thank you for the quick solution. I had a discussion with Tridonic and OpenAIS and they are able to implement their use cases with this change.

**Comment by yogpan01** [comment]
@anttiylitokola Can you update unit tests for this ?

**Comment by EduardPon** [comment]
Hello,

When can we expect this change will be deployed to receive the update via yotta?

**Comment by anttiylitokola** [comment]
Hi,
Changes are now pushed to yotta. Version is 1.13.0.

**Pull request merged**
