### PR TITLE
Adding error code for FORBIDDEN from mDS.

### PR DESCRIPTION
**Pull request by yogpan01**
In case the server returns error as FORBIDDEN, there should be no
re-connection logic triggered on client side.

### CODE REVIEW

**Comment by yogpan01** [comment]
@anttiylitokola

**Comment by anttiylitokola** [comment]
+1

**Comment by teetak01** [comment]
rebuild

**Comment by kjbracey-arm** [comment]
Surely most, or even all, 4.xx codes ("Client Error") should not retry? Generally 5.xx codes ("Server Error") should be the ones that retry.

If you don't want a global 4.xx check, at a minimum you should add the 4.xx codes that are explicitly documented in RFC 7252 as "don't repeat": Unauthorized & Bad Option.

**Comment by teetak01** [comment]
rebuild

**Comment by anttiylitokola** [comment]
rebuild

**Comment by yogpan01** [comment]
rebuild

**Comment by yogpan01** [comment]
rebuild

**Pull request merged**
