### PR TITLE
Skip write attribute values if client responds with bad request

### PR DESCRIPTION
**Pull request by anttiylitokola**
Fixes error:
* IOTCLT-223 - Write attribute operation values are updated even if client responds with Bad request

### CODE REVIEW

**Comment by anttiylitokola** [comment]
Re-trigger build

**Comment by anttiylitokola** [comment]
Re-trigger CI build

**Comment by anttiylitokola** [comment]
re-trigger CI build

**Comment by anttiylitokola** [comment]
mbed CI Jenkins --> Rebuild

**Comment by anttiylitokola** [comment]
@yogpan01, can you check this?

**Comment by yogpan01** [comment]
+1

**Pull request merged**
