### PR TITLE
Updating docs related with reconnection logic and configuration.

### PR DESCRIPTION
**Pull request by yogpan01**

### CODE REVIEW

**Comment by yogpan01** [comment]
@peknis01 Please review 
@anttiylitokola FYI

**Comment by peknis01** [comment]
Reviewed and edited now. Please check once again.

**Comment by yogpan01** [comment]
@peknis01 We will not merge this PR now but later. As for now, we just review it and keep it ready for later merge and publish.

**Comment by peknis01** [comment]
Roger that.

**Comment by teetak01** [comment]
rebuild

**Comment by anttiylitokola** [comment]
@peknis01, @yogpan01 can you check the "Write" chapter changes?

**Comment by peknis01** [comment]
Checked the language and did a couple of minor edits.

**Pull request merged**
